let searchKeywords = [
    "how to remove ads from youtube in inspect element",
    "how to remove ads from youtube",
    "how to create folder in github",
    "how to unzip a zip file",
    "how to hack google",
    "what is google",
    "what time is it bangladesh",
    "what is hacking",
    "Learn Object Orianted Javascript",
    "realme c25 price in bangladesh",
    "rog 3 price in bd",
    "autocomplete search box using javascript codepen",
    "alesha mart contact number",
    "ablota hack store",
    "asphalt 8 airborne hack",
    "buffer marketing library",
    "facebook marketing bangla tutorial",
    "facebook business manager",
    "google add manager",
    "seo in digital marketing",
    "wordpress powers 31 of the internet",
    "wordpress security",
]